baseURL = 'https://lexleesch.com/'
languageCode = 'en-us'
title = 'Lex Website'
theme = 'cyberscape'

# Enable this for tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true

# Add menu links to things from /content/ here (eg. markdown.md)
[[menu.main]]
name = "other-page"
url = "/other-page/"
weight = 1

[[menu.main]]
name = "photobooths"
url = "https://umap.openstreetmap.fr/en/map/lex-and-alanis-photo-booths_961199?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false&captionMenus=true"
weight = 2